apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gpla414ns-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gpla414ns-go 
  name: gpla414ns-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gpla414ns-go 
